#include <SDL3/SDL.h>
#include <cstdio>
#include <cstring>
#include <vector>

#include "backend/renderer/IRenderDevice.h"
#include "backend/renderer/sdl_gpu/SDLGPURenderDevice.h"
#include "backend/renderer/opengl/GLRenderDevice.h"
#include "backend/renderer/CommandBuffer.h"

// Embedded shader headers (generated by CMake)
#include "hello_compute_spv.h"
#ifdef QGAME_HAS_DXIL_SHADERS
#include "hello_compute_dxil.h"
#endif

int main(int argc, char** argv) {
    if (!SDL_Init(SDL_INIT_VIDEO)) {
        printf("SDL_Init failed: %s\n", SDL_GetError());
        return 1;
    }

    SDL_Window* window = SDL_CreateWindow(
        "hello_compute", 800, 600, SDL_WINDOW_VULKAN | SDL_WINDOW_HIDDEN);
    if (!window) {
        window = SDL_CreateWindow(
            "hello_compute", 800, 600, SDL_WINDOW_OPENGL | SDL_WINDOW_HIDDEN);
    }
    if (!window) {
        printf("[SKIP] SDL_CreateWindow failed: %s (headless environment?)\n", SDL_GetError());
        SDL_Quit();
        return 0;  // Not a failure - just can't run in headless env
    }

    // Create SDL GPU render device
    backend::SDLGPURenderDevice device(window);
    device.init();

    // Check if device initialized properly
    if (!device.gpuDevice()) {
        printf("[SKIP] GPU device not initialized (headless environment?)\n");
        device.shutdown();
        SDL_DestroyWindow(window);
        SDL_Quit();
        return 0;
    }
    printf("[OK] GPU device initialized\n");
    fflush(stdout);

    // Create input buffer
    backend::BufferDesc inputDesc{};
    inputDesc.size = 1024 * sizeof(uint32_t);
    inputDesc.usage = backend::BufferUsage::Storage;
    
    std::vector<uint32_t> inputData(1024);
    for (uint32_t i = 0; i < 1024; ++i) {
        inputData[i] = i;
    }
    inputDesc.initialData = inputData.data();
    
    printf("[DEBUG] Creating input buffer...\n");
    fflush(stdout);
    
    inputDesc.initialData = nullptr;  // Don't upload data yet - test buffer creation
    
    auto inputBuffer = device.createBuffer(inputDesc);
    printf("[DEBUG] createBuffer returned\n");
    fflush(stdout);
    
    if (!inputBuffer.valid()) {
        printf("[FAIL] Failed to create input buffer\n");
        device.shutdown();
        SDL_DestroyWindow(window);
        SDL_Quit();
        return 1;
    }
    printf("[OK] Created input buffer (1024 uint32)\n");
    fflush(stdout);

    // Create output buffer
    backend::BufferDesc outputDesc{};
    outputDesc.size = 1024 * sizeof(uint32_t);
    outputDesc.usage = backend::BufferUsage::Storage;
    
    auto outputBuffer = device.createBuffer(outputDesc);
    printf("[DEBUG] createBuffer returned for output\n");
    fflush(stdout);
    
    if (!outputBuffer.valid()) {
        printf("[FAIL] Failed to create output buffer\n");
        device.destroyBuffer(inputBuffer);
        device.shutdown();
        SDL_DestroyWindow(window);
        SDL_Quit();
        return 1;
    }
    printf("[OK] Created output buffer (1024 uint32)\n");
    fflush(stdout);

    // Select shader based on backend
    const uint8_t* shaderCode = nullptr;
    size_t shaderSize = 0;
    
#ifdef QGAME_HAS_DXIL_SHADERS
    if (hello_compute_dxil_size > 1) {
        shaderCode = hello_compute_dxil;
        shaderSize = hello_compute_dxil_size;
        printf("[INFO] Using DXIL compute shader\n");
    } else
#endif
    if (hello_compute_spv_size > 1) {
        shaderCode = hello_compute_spv;
        shaderSize = hello_compute_spv_size;
        printf("[INFO] Using SPIRV compute shader\n");
    }

    if (shaderCode && shaderSize > 0) {
        backend::ComputePipelineDesc pipelineDesc{};
        pipelineDesc.code = shaderCode;
        pipelineDesc.codeSize = shaderSize;
        pipelineDesc.entryPoint = "main";
        pipelineDesc.threadCountX = 64;
        pipelineDesc.threadCountY = 1;
        pipelineDesc.threadCountZ = 1;
        pipelineDesc.numReadwriteStorageBuffers = 2;
        
        auto pipeline = device.createComputePipeline(pipelineDesc);
        if (pipeline.valid()) {
            printf("[OK] Created compute pipeline\n");
            device.destroyComputePipeline(pipeline);
        } else {
            printf("[WARN] Failed to create compute pipeline\n");
        }
    } else {
        printf("[WARN] No compute shader compiled (compile hello_compute.comp/hlsl)\n");
    }

    // Cleanup
    device.destroyBuffer(inputBuffer);
    device.destroyBuffer(outputBuffer);
    device.shutdown();
    
    SDL_DestroyWindow(window);
    SDL_Quit();
    
    printf("\n[RESULT] S2 Compute Pipeline - Buffer API verified\n");
    return 0;
}
